export const shop = {
  name: 'GYOZA WOOD',
  date: '2026-07-06',
  owner: '店長 葉若睦',
  slaTarget: '15 分鐘內出餐',
};

// 原物料主檔:欄位與 sku 沿用「AI excel 課程」的物料主檔(M001-M012),
// 讓學生在 excel 課看到的 M001 麵皮,在這裡是同一個東西。
// ops-agent-lab/inventory_sample.csv 是同一份資料的 CSV 版,兩邊必須逐欄一致。
export const menuItems = [
  {
    sku: 'M001',
    product: '麵皮',
    zone: '煎台區',
    stock: 200,
    reorderPoint: 500,
    reserved: 120,
    owner: '王先生',
    channel: 'LINE OA',
    unitPrice: 1,
  },
  {
    sku: 'M002',
    product: '豬絞肉',
    zone: '煎台區',
    stock: 30,
    reorderPoint: 10,
    reserved: 6,
    owner: '林小姐',
    channel: 'LINE OA',
    unitPrice: 180,
  },
  {
    sku: 'M003',
    product: '高麗菜',
    zone: '冷藏區',
    stock: 40,
    reorderPoint: 15,
    reserved: 5,
    owner: '陳先生',
    channel: 'LINE OA',
    unitPrice: 45,
  },
  {
    sku: 'M004',
    product: '韭菜',
    zone: '冷藏區',
    stock: 0,
    reorderPoint: 5,
    reserved: 2,
    owner: '陳先生',
    channel: 'LINE OA',
    unitPrice: 80,
  },
  {
    sku: 'M005',
    product: '玉米粒',
    zone: '冷藏區',
    stock: 8,
    reorderPoint: 3,
    reserved: 2,
    owner: '陳先生',
    channel: 'LINE OA',
    unitPrice: 65,
  },
  {
    sku: 'M006',
    product: '酸辣湯料',
    zone: '湯飲區',
    stock: 20,
    reorderPoint: 8,
    reserved: 4,
    owner: '林小姐',
    channel: 'LINE OA',
    unitPrice: 90,
  },
  {
    sku: 'M007',
    product: '豆漿原料',
    zone: '湯飲區',
    stock: 12,
    reorderPoint: 4,
    reserved: 3,
    owner: '李小姐',
    channel: 'LINE OA',
    unitPrice: 90,
  },
  {
    sku: 'M008',
    product: '紅茶茶包',
    zone: '湯飲區',
    stock: 10,
    reorderPoint: 4,
    reserved: 2,
    owner: '李小姐',
    channel: 'LINE OA',
    unitPrice: 110,
  },
  {
    sku: 'M009',
    product: '外帶盒',
    zone: '包材區',
    stock: 300,
    reorderPoint: 150,
    reserved: 60,
    owner: '黃先生',
    channel: '外送平台',
    unitPrice: 3,
  },
  {
    sku: 'M010',
    product: '外帶碗',
    zone: '包材區',
    stock: 50,
    reorderPoint: 100,
    reserved: 15,
    owner: '黃先生',
    channel: '外送平台',
    unitPrice: 2,
  },
  {
    sku: 'M011',
    product: '外帶杯',
    zone: '包材區',
    stock: 200,
    reorderPoint: 100,
    reserved: 30,
    owner: '黃先生',
    channel: '外送平台',
    unitPrice: 2,
  },
  {
    sku: 'M012',
    product: '醬料包',
    zone: '包材區',
    stock: 500,
    reorderPoint: 200,
    reserved: 80,
    owner: '黃先生',
    channel: '外送平台',
    unitPrice: 1,
  },
];

export const sampleOrders = [
  {
    id: 'GW-20260706-018',
    customer: '潘海伶',
    channel: '外送平台',
    status: '待製作',
    priority: 'high',
    zone: '煎台區',
    amount: 105,
    eta: '14:30',
  },
  {
    id: 'GW-20260706-021',
    customer: '馮川翔',
    channel: 'LINE OA',
    status: '製作中',
    priority: 'medium',
    zone: '煎台區',
    amount: 95,
    eta: '15:10',
  },
  {
    id: 'GW-20260706-025',
    customer: '錢阿儂',
    channel: '外送平台',
    status: '待取餐',
    priority: 'low',
    zone: '包材區',
    amount: 160,
    eta: '16:20',
  },
  {
    id: 'GW-20260706-031',
    customer: '校園排球隊',
    channel: 'LINE OA',
    status: '缺料等待',
    priority: 'high',
    zone: '冷藏區',
    amount: 350,
    eta: '13:50',
  },
];

export const zones = [
  { id: 'A', label: '煎台區', utilization: 82, status: 'watch' },
  { id: 'B', label: '包材區', utilization: 61, status: 'watch' },
  { id: 'C', label: '冷藏區', utilization: 88, status: 'risk' },
  { id: 'D', label: '湯飲區', utilization: 54, status: 'good' },
];
